language: python
sudo: false
dist: trusty
install:
- pip install --user tox
script:
- tox
deploy:
  provider: pypi
  user: lwcolton
  password:
    secure: i+rUnYPXFKv0dhkl4FsUxDyn3eI8coeH+4ZnvNgSB7AhAZaBP1QYXUFr6mrDJ1jHNpCGF1N+7G3NFqw28q0Uv1l5OZnFTRK1YtNiCGA+xXXkiBA3Py9TOc8m7e0CExxxsa/Ip/5Gc6AbHnXZ/euA/1d7419SlMsHxrX/W3fi9KuiHqKKzMZdFljqgHBpu7szccKZ3qQqRdSBmnwDkpGzX1Gf3RrYFVkmNvm5eDvEHMNzBqUGduAYPKaRhdA1CcsFpg9eV1l0jceGHXGf3u8ZbVt0JJgebpQIQYBN02NBA11XdO+eVkyCt539VgUOWDrg+kBmsXEt4ctBIHk8+5NhKht7doPv5DFbGti5jdsH39Oht/mv+iUpYuZ9N2v9iUIaufHU4bVgatYhZh0CHBaAsVwpUSq/KFgyfTTz58rjDhwLD6GfILD+OlQj3CLsb8p6ERc2G66IbArSw/UcBRdpvcqFjN3w81Qh6li1zsmmk/OIbByZn2hgMxsCFvXvFTNxXBs8DX7d3x2U3ufni373M39r0XIyOVcK4XCnNsJ5y5Jy0UCpCX2jGJ/PZVhzoxWYHl2Xu3MiaSph/1hqGk3ldbh1AQvimBDAbI8DWqempgQiCDsieUACv2XeifJHSsAahbi6ArbnoP9dgWYz3kOnM2UILP2FL2fG1uU1wm2dn2U=
  on:
    branch: master
    tags: true
